---
title: "R Notebook"
output: html_notebook
---

Begrundelser for valg i ANN: 
NOTE: 
relu is very computational efficient, quick convergence. sigmoid is computational 
expensive but gives clear predictions.

Input shape = 4 because we have four variables. 

kernel_initializer = the start weights, random_normal takes random values from a normal distribution

units = number of hidden units, input should be same as amount of variables, output layer should be 1 when it is a classifier like ours, hidden layer somewhere in between.

binary_crossentropy is the default and preferred loss function for binary classification problem

Learning objectives:
A student who has met the objectives will be able to:

Week 1
[ ] Explain why reproducible data analysis is important, as well as identify relevant challenges 
    and explain replicability versus reproducibility
[ ] Describe the components of a reproducible data analysis
[X] Create an RStudio Cloud account and run cloud based sessions
[X] Master the very basics of R
[X] Navigate the RStudio IDE
[X] Create, edit and run a basic RMarkdown document

Week 2
[X] Use ggplot to visualize multilayer data from e.g. high-througput -omics platforms
[X] Decipher the components of a ggplot

Week 3
[X] Understand and apply the 6 basic dplyr verbs filter(), arrange(), select(), mutate(),
    summarise() and group_by()
[X] Understand and apply the additional verbs count(), drop_na(), View()
[X] Combine dplyr verbs to form a data manipulation pipeline using the pipe %>% operator
[X] Decipher the components and functions hereof, of a dplyr pipeline

Week 4
[X] Understand and apply the various str_*() functions for string manipulation
[X] Understand and apply the family of *_join() functions for combining data sets
[X] Understand and apply pivot_wider() and pivot_longer()
[X] Use factors in conjugation with plotting categorical data using ggplot

Week 5
[X] Understand and apply simple map() functions for element-wise function application
[?] Understand and apply grouped supervised models to form nested model objects
[X] Understand and apply the tidy() function for tidying various model objects
[X] Perform a principal component analysis for dimension reduction of high dimensional data
[-] Perform an unsupervised k-means clustering of high dimensional data

Week 6
[ ] Explain why reproducible data analysis is important, as well as identify relevant challenges 
    and explain replicability versus reproducibility
[ ] Describe the components of a reproducible data analysis
[X] Use RStudio and github for collaborative analysis projects

Week 7
[X] Train and apply a simple basic machine learning model based on a neural network with 
    Keras / Tensorflow in R

Week 8
[-] Prepare a simple R package for distributing documented functions
[-] Using relevant online ressources to independently obtain new and expand on existing knowledge 
    of R
  
Week 9
[X] Prepare a simple shiny application for distributing interactive data exploration
[X] Using relevant online ressources to independently obtain new and expand on existing knowledge 
    of R